### ISSUE TITLE
Error in expect'

### ISSUE THREAD

**Issue by artix41** [QuantumBFS/Yao.jl#201] opened 2019-09-23 20:36 UTC
I'm trying to run this code
```julia
v_unitary = variational_circuit(n)
v_circuit = chain(n+1, control(1, 2:n+1=>v_unitary));
expect'(put(n+1, 1=>Z), zero_state(n+1) => v_circuit)
```
but get the following error:
```julia
MethodError: no method matching dynamicize(::Array{Int64,1})
```

Note that the following code is working:
```julia
v_unitary = chain(n, repeat(H, 1:n))
v_circuit = chain(n+1, control(1, 2:n+1=>v_unitary));
expect'(put(n+1, 1=>Z), zero_state(n+1) => v_circuit)
```

**Comment by Roger-luo** [comment] 2019-09-23 21:07
I can't reproduce the error on my laptop, but it seems to be fixed in LuxurySparse now.

**Comment by Roger-luo** [comment] 2019-09-24 01:42
OK, I did a bit investigation, this is error is triggered by `control` gate on a matrix representation. This should be fixed by the patch in LuxurySparse.

**Closed** 2019-09-24 05:26 UTC

**Comment by GiggleLiu** [comment] 2019-09-24 05:32
Yeah, this is a bug, with the master branch of `LuxurySparse`, it should work now.
(By typing `] dev LuxurySparse` in a Julia REPL).

Now the performance of controlled large block is not fully optimized, it calls into the matrix representation of target block, which will cause allocations. use `cache` to avoided invoking `mat` multiple times
```
v_circuit = chain(n+1, control(1, 2:n+1=>cache(v_unitary)));
```

please let us know if you want it be more performant.
