### ISSUE TITLE
CuYao compiles depending on value, not depending on type

### ISSUE THREAD

**Issue by jlbosse** [QuantumBFS/Yao.jl#362] opened 2022-04-20 09:37 UTC
It seems like CuYao recompiles `apply!` every time the parameters of a circuit are changed, even though the circuit is still the same. This is in contrast to running a circuit on the CPU and and not on the GPU where compilation happens only once when running  a circuit for the first time and then all future runs are fast when changing the parameters. See the following MWE:

```julia
using Yao, Yao.AD, Yao.EasyBuild
using CuYao
import CUDA

n = 10
d = 5
circuit = variational_circuit(n, d)

cureg = zero_state(n) |> cu
reg = zero_state(n) 

# every time this block gets run the first `apply!()` takes much longer than the second `appply!()`
begin
    cureg.state .= 0.
    @CUDA.allowscalar cureg.state[1] = 1.
    dispatch!(circuit, :random)
    @time apply!(cureg, circuit)
    @time apply!(cureg, circuit)
end

# only the very first time this block gets run the first `apply!()` invokes a compilation pass, after
# that the first `apply!()` and the second apply always take roughly the same time.
begin
    reg.state .= 0.
    reg.state[1] = 1.
    dispatch!(circuit, :random)
    @time apply!(reg, circuit)
    @time apply!(reg, circuit)
end
```

**Comment by GiggleLiu** [comment] 2022-04-20 16:39
Just confirmed this issue, it was due to the use of closure when writing kernel functions, will fix it later today. Thanks for reporting the bug!

**Comment by GiggleLiu** [comment] 2022-04-21 00:01
You issue will be fixed by this PR: https://github.com/QuantumBFS/CuYao.jl/pull/74
Thanks again for the bug report!

**Comment by GiggleLiu** [comment] 2022-04-22 03:25
The PR in CuYao has been merged and is being tagged, I will close this issue for now. Feel free to reopen it if the patch does not fix your issue.

**Closed by GiggleLiu** 2022-04-22 03:25 UTC
Labels: bug

**Comment by jlbosse** [comment] 2022-04-22 12:20
Worked perfectly, thanks
