### ISSUE TITLE
change chain interface

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/Yao.jl#174] opened 2019-04-13 05:44 UTC
Possible BUG with function `chain`.

Example Code:
```
julia> c = put(3, 3=>X)
Total: 3, DataType: Complex{Float64}
put on (3)
└─ X gate

julia> chain(c, c)
Total: 3, DataType: Complex{Float64}
chain
├─ put on (3)
│  └─ X gate
└─ put on (3)
   └─ X gate

julia> chain(3, c, c)
Total: 3, DataType: Complex{Float64}
chain
├─ put on (3)
│  └─ X gate
└─ put on (3)
   └─ X gate

julia> chain(c)
Total: 3, DataType: Complex{Float64}
chain
└─ put on (3)
   └─ X gate

julia> chain(3, c)
ERROR: MethodError: no method matching iterate(::PutBlock{3,1,XGate{Complex{Float64}},Complex{Float64}})
```

**Comment by GiggleLiu** [comment] 2019-04-13 06:52
This interface is deliberately remove since `chain(1, [X, X, X])` and `chain(1, another chain)` with different behavior can be confusing.

But, you are right, maybe the consistency here is decreased. I would suggest
1. keep it is
2. or remove `chain(n, a, b, c)` and allows only `chain(n, [a, b, c])` construction.

@Roger-luo which one do you prefer?

**Comment by frankwswang** [comment] 2019-04-13 08:47
I don't quite understand what you mean by 

> `chain(1, [X, X, X])` and `chain(1, another chain)` with different behavior can be confusing.

Do you mean we should always write `chain` function like `chain(n, [ChainBlock])` or `chain(n, [ChainBlock1, ChainBlock2])`?

**Comment by GiggleLiu** [comment] 2019-04-13 08:58
`chain(1, [X, X, X])` and `chain(1, chain(X, X, X))`,
Since there is a subtle relation between chains and lists.

**Comment by Roger-luo** [comment] 2019-04-13 09:03
It's just a bug, fixed with next coming release. I forget to implement `chain(n, block)` , it is indeed a rare use case.

**Comment by GiggleLiu** [comment] 2019-04-13 09:12
Delete it if it is not necessary, especially when it turns out to be confusing.

Here, `necessary` means one can not do something without it.

**Comment by Roger-luo** [comment] 2019-04-13 09:14
`chain(n, blocks...)` is definitely drier than `chain(n, list)` and it avoids the problem of the following

```julia
list = []
for k in 1:10
   push!(list, someblock)
end
chain(n, list) # error
```

I'd rather delete `chain(n, [])` since if one really want to use a list, use the constructor and solve the type mismatch error himself.

**Comment by Roger-luo** [comment] 2019-04-13 09:16
The whole point of these functions is to make code drier and more friendly. And I don't see which part is confusing, since they have completely different types in completely different type tree.

**Comment by GiggleLiu** [comment] 2019-04-13 09:28
> chain(n, blocks...) is definitely drier than chain(n, list)

Interesting point, please define `drier`

In my opinion, less interface usually indicates a drier design.

> And I don't see which part is confusing

`chain` falls into the category of iterator. This is the confusing part.

> in fact, chain(n, list) is duplicated with the constructor

This is not a reason for using another interface.

**Comment by Roger-luo** [comment] 2019-04-13 09:36
**drier** means don't let users to type extra information, only write what is necessary, keep the required input minimal. Drier means the users code is drier, it doesn't mean the code base of package is drier.

> chain falls into the category of iterator. This is the confusing part.

This is fixed.

```
chain(3, c)
```

now this will work as well

```julia
chain(3, itr)
```

this will work as well, and it is the key point to make things like QFT simple and readable.

```julia
chain(3, put(i=>X) for i in 1:3)
```

```
This is not a reason for using another interface.
```

What I mean is, if you really want to have less interfaces, delete `chain(n, list)` this is the real extra thing we don't need.

**Comment by GiggleLiu** [comment] 2019-04-13 10:35
I notice that `julia> chain(1, chain(X,X,X))` is runable. This should not work. This is the real bug.

**Comment by Roger-luo** [comment] 2019-04-13 10:49
Yes, this is not expected behaviour, it is fixed in master. It has the same behaviour as other blocks

```julia
julia> chain(1, chain(X, Y, Z))
nqubits: 1, datatype: Complex{Float64}
chain
└─ chain
   ├─ X gate
   ├─ Y gate
   └─ Z gate

```

**Comment by Roger-luo** [comment] 2019-12-07 13:01
I think this is resolved now.

**Closed by Roger-luo** 2019-12-07 13:01 UTC
Labels: discussion, need test
